spring:
  application:
    name: rewards-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/rewardsdb}
      auto-index-creation: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    com.example.rewards_program_api: DEBUG
    org.springframework.data.mongodb: DEBUG



