spring:
  application:
    name: rewards-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/rewardsdb}
      auto-index-creation: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

logging:
  level:
    com.portalsplatform.api: INFO
    org.springframework.data.mongodb: WARN

# Security Configuration
api:
  security:
    enabled: true
    header-name: X-API-Key
    # Development fallback - production should override via environment
    api-key: ${API_KEY:dev-demo-key-12345}
    rate-limit:
      enabled: true
      max-requests-per-minute: 100

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Schema Validation Rules
schema-validation:
  rules:
    - path: /api/customers
      method: POST
      schema: customer-schema.json
    - path: /api/transactions
      method: POST
      schema: TransactionRequest.schema.json



